# Generated by Django 4.2.7 on 2025-04-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('team_invite', 'Team Invitation'), ('team_join', 'Team Join'), ('team_leave', 'Team Leave'), ('project_update', 'Project Update'), ('project_feedback', 'Project Feedback'), ('system', 'System Notification')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
